{
    'name': 'Service Order',
    'version': '19.0.1.0.0',
    'category': 'Services',
    'summary': 'Gestión de Órdenes de Servicio independiente',
    'author': 'Alphaqueb Consulting',
    'depends': ['sale', 'account', 'fleet'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/service_order_sequence.xml',
        'views/service_order_views.xml',
        'views/service_order_manifest_description_view.xml',
        'reports/service_order_report.xml',
        'views/service_order_print_button.xml',
        'views/sale_order_inherit.xml',
        'views/service_order_invoice_button.xml',
        'views/product_template_view.xml',
        'views/service_order_invoice_view_button.xml',
        'views/account_move_service_link_view.xml',
        'views/account_move_form_extension.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}